services:
  
  timescaledb:
    image: timescale/timescaledb:2.14.2-pg16
    command: postgres -c 'max_connections=500'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - nb_studio_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nb_studio_db
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: timescaledb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d 'user=timescaledb dbname=nb_studio_db'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
  
  nbomber-studio:
    image: nbomberdocker/nbomber-studio:latest
    ports:
      - "5333:8080"
    depends_on:
      timescaledb:
        condition: service_healthy
    env_file:
      - .env/nb_studio.env

volumes:
  nb_studio_data:
    driver: local